### ISSUE TITLE
renaming this library and repo

### ISSUE THREAD

**Issue by JustinBeckwith** [google/standardts#275]
When we originally came up with the idea for this tool, it was heavily inspired by `standardjs`.  We talked about naming it `standardts`, but that name on `npm` was taken.  Well...  the owner of that library has graciously agreed to give us the rights to that package if we want them:
https://github.com/krzkaczor/standardts/issues/7

My proposal:
- We rename the library heading into the 1.x release.  
- Since `standardts` already has a 1.0, we would skip straight to `2.0`
- We rename this repo to be `google/standardts`
- We deprecate the existing `gts` package, and send users to `standardts`

Looking for feedback and thoughts!  @google/google-node-team

**Comment by JustinBeckwith** [comment]
We do not today.  However - with the move towards `eslint` in the TypeScript toolchain and away from `tslint`, it's entirely possible that our future for this is a lightweight tool on top of `standard`.

That having been said - I hear what you're saying.  My big concern today is that `gts` never really conveyed what this library does.  I was looking at this as an opportunity to use a familiar name for a tool that we respect and is quite similar to what we do.

**Comment by JustinBeckwith** [comment]
Also - just want to make sure @feross has no concerns here.

**Comment by kjin** [comment]
I'm not sold on the importance of conveying any particularly strong meaning with the name of this module, I guess since I don't see any value out of marketing this module as the "Google-endorsed formatting tool" at all, _especially_ if it is a lightweight tool that just calls through to a real formatting module that we didn't write (whether or not that's `standard`). Along the same vein I don't think it makes sense to share a name with an existing formatting standard just because it's "similar". I think `gts` is a suitable name, it's a sensible acronym that's easy to type.

**Comment by JustinBeckwith** [comment]
I can get behind that :) @DominicKramer, I think you preferred the `gts` name as well?  Given that we have more votes to stick with gts than to rename, I'm happy to close this out.

**Comment by feross** [comment]
Just saw this issue! I know the ship has sailed already, but fwiw I would have be fine with you calling it `standardts`. ❤️

**Comment by JustinBeckwith** [comment]
@feross thanks for the blessing!  We ultimately decided to stick with `gts`, but thanks again for the inspiration behind the project.
